---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xray-core.fullname" . }}-config-json
  labels:
    {{- include "xray-core.labels" . | nindent 4 }}
data:
  config.json: |-
    {{- .Values.configJson | nindent 4 }}