apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xray-core.fullname" . }}-tls-secret-replica
  labels:
    {{- include "xray-core.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.tlsSecret.annotations | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.key: "{{ .Values.tlsSecret.key }}"
  tls.crt: "{{ .Values.tlsSecret.crt }}"